/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RadioPackage;

import javax.swing.JSlider;

/**
 *
 * @author wadeowen
 */
public class GUIRadio extends javax.swing.JFrame {

    /**
     * Creates new form GUIRadio
     */
    private Radio laRadio = new Radio();
    private float max;
    private float min;
    private float step;
    
    public GUIRadio() {
        initComponents();
        ApagarRadio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnOffButton = new javax.swing.JToggleButton();
        AMButton = new javax.swing.JToggleButton();
        FMButton = new javax.swing.JToggleButton();
        StationLabel = new javax.swing.JLabel();
        StatBut1 = new javax.swing.JButton();
        StatBut2 = new javax.swing.JButton();
        StatBut3 = new javax.swing.JButton();
        StatBut4 = new javax.swing.JButton();
        StatBut5 = new javax.swing.JButton();
        StatBut6 = new javax.swing.JButton();
        StatBut7 = new javax.swing.JButton();
        StatBut8 = new javax.swing.JButton();
        StatBut9 = new javax.swing.JButton();
        StatBut10 = new javax.swing.JButton();
        StatBut11 = new javax.swing.JButton();
        StatBut12 = new javax.swing.JButton();
        PlusButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OnOffButton.setText("Off");
        OnOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnOffButtonActionPerformed(evt);
            }
        });

        AMButton.setText("AM");
        AMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMButtonActionPerformed(evt);
            }
        });

        FMButton.setText("FM");
        FMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMButtonActionPerformed(evt);
            }
        });

        StationLabel.setText("jLabel1");

        StatBut1.setText("1");
        StatBut1.setMaximumSize(new java.awt.Dimension(26, 34));

        StatBut2.setText("2");

        StatBut3.setText("3");

        StatBut4.setText("4");

        StatBut5.setText("5");

        StatBut6.setText("6");

        StatBut7.setText("7");

        StatBut8.setText("8");

        StatBut9.setText("9");

        StatBut10.setText("10");

        StatBut11.setText("11");

        StatBut12.setText("12");

        PlusButton.setText("+");
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        MinusButton.setText("-");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FMButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StationLabel)
                            .addComponent(OnOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AMButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatBut1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(StatBut7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatBut2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(StatBut8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatBut3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(StatBut9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(StatBut4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatBut10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StatBut5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatBut11, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StatBut6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatBut12, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnOffButton)
                    .addComponent(AMButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FMButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StationLabel)
                    .addComponent(PlusButton)
                    .addComponent(MinusButton))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatBut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatBut4)
                    .addComponent(StatBut5)
                    .addComponent(StatBut2)
                    .addComponent(StatBut3)
                    .addComponent(StatBut6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatBut7)
                    .addComponent(StatBut8)
                    .addComponent(StatBut9)
                    .addComponent(StatBut10)
                    .addComponent(StatBut11)
                    .addComponent(StatBut12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnOffButtonActionPerformed
        laRadio.OnOff();
        StationLabel.setText(laRadio.getStation());
        if (laRadio.isOn){
            OnOffButton.setText("ON");
            EncenderRadio();
        } else {
            OnOffButton.setText("OFF");
            ApagarRadio();
        }
    }//GEN-LAST:event_OnOffButtonActionPerformed

    private void AMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMButtonActionPerformed
        FMButton.setSelected(false); 
        laRadio.changeFrecuency();
    }//GEN-LAST:event_AMButtonActionPerformed

    private void FMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMButtonActionPerformed
        AMButton.setSelected(false); 
        laRadio.changeFrecuency();
    }//GEN-LAST:event_FMButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        laRadio.Backward();
        StationLabel.setText(laRadio.getStation());
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
        laRadio.Forward();
        StationLabel.setText(laRadio.getStation());
    }//GEN-LAST:event_PlusButtonActionPerformed

    private void ApagarRadio(){
       StationLabel.setVisible(false);
       FMButton.setVisible(false);
       AMButton.setVisible(false);
       PlusButton.setVisible(false);
       MinusButton.setVisible(false);
       StatBut1.setVisible(false);
       StatBut2.setVisible(false);
       StatBut3.setVisible(false);
       StatBut4.setVisible(false);
       StatBut5.setVisible(false);
       StatBut6.setVisible(false);
       StatBut7.setVisible(false);
       StatBut8.setVisible(false);
       StatBut9.setVisible(false);
       StatBut10.setVisible(false);
       StatBut11.setVisible(false);
       StatBut12.setVisible(false);
    }
    
    private void EncenderRadio(){
       StationLabel.setVisible(true);
       FMButton.setVisible(true);
       AMButton.setVisible(true);
       PlusButton.setVisible(true);
       MinusButton.setVisible(true);
       StatBut1.setVisible(true);
       StatBut2.setVisible(true);
       StatBut3.setVisible(true);
       StatBut4.setVisible(true);
       StatBut5.setVisible(true);
       StatBut6.setVisible(true);
       StatBut7.setVisible(true);
       StatBut8.setVisible(true);
       StatBut9.setVisible(true);
       StatBut10.setVisible(true);
       StatBut11.setVisible(true);
       StatBut12.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AMButton;
    private javax.swing.JToggleButton FMButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JToggleButton OnOffButton;
    private javax.swing.JButton PlusButton;
    private javax.swing.JButton StatBut1;
    private javax.swing.JButton StatBut10;
    private javax.swing.JButton StatBut11;
    private javax.swing.JButton StatBut12;
    private javax.swing.JButton StatBut2;
    private javax.swing.JButton StatBut3;
    private javax.swing.JButton StatBut4;
    private javax.swing.JButton StatBut5;
    private javax.swing.JButton StatBut6;
    private javax.swing.JButton StatBut7;
    private javax.swing.JButton StatBut8;
    private javax.swing.JButton StatBut9;
    private javax.swing.JLabel StationLabel;
    // End of variables declaration//GEN-END:variables
}
